if(CMAKE_VS_PLATFORM_NAME STREQUAL "Gaming.Xbox.Scarlett.x64" OR NS_GDKX_BUILDFOR_XBOX_SERIES_X) # Series X
    set_property(GLOBAL PROPERTY NS_CMAKE_PLATFORM_NAME "Scarlett")
    set_property(GLOBAL PROPERTY NS_CMAKE_PLATFORM_PREFIX "GDKX")
    set_property(GLOBAL PROPERTY NS_CMAKE_PLATFORM_POSTFIX "GDKX")
endif()